# fly.toml app configuration file generated for poopy-minecraft on 2024-10-29T09:54:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poopy-minecraft'
primary_region = 'atl'

[build]
  image = 'itzg/minecraft-server:java21-alpine'

[env]
  ALLOW_FLIGHT = 'TRUE'
  AUTOSTOP_PERIOD = '10'
  AUTOSTOP_TIMEOUT_EST = '3600'
  AUTOSTOP_TIMEOUT_INIT = '1800'
  DIFFICULTY = 'normal'
  ENABLE_AUTOSTOP = 'TRUE'
  ENABLE_ROLLING_LOGS = 'true'
  ENABLE_WHITELIST = 'true'
  ENFORCE_WHITELIST = 'true'
  EULA = 'true'
  INIT_MEMORY = '512M'
  LEVEL = 'world1'
  MAX_MEMORY = '3G'
  MODE = 'survival'
  MOTD = 'blame dani for the name'
  OPS_FILE = 'https://github.com/jfreedman0212/mc-vanilla-server/releases/download/v0.0.1/ops.json'
  OVERRIDE_OPS = 'true'
  OVERRIDE_WHITELIST = 'true'
  RCON_CMDS_STARTUP = "        /gamerule keepInventory true\n        /gamerule playersSleepingPercentage 1\n    "
  SEED = '4354585255707245098'
  SERVER_NAME = 'poopy-minecraft'
  SPAWN_PROTECTION = '0'
  TYPE = 'VANILLA'
  VANILLATWEAKS_SHARECODE = 'NmOAok,vXcnMe,yoptLT,AtuqRB,zJ84rA'
  VERSION = '1.21.3'
  WHITELIST_FILE = 'https://github.com/jfreedman0212/mc-vanilla-server/releases/download/v0.0.1/whitelist.json'

[[mounts]]
  source = 'mc_data'
  destination = '/data'

[http_service]
  internal_port = 25565
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 25565

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
