# fly.toml app configuration file generated for mc-igwt on 2024-11-03T20:16:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mc-igwt'
primary_region = 'atl'

[build]
image = 'itzg/minecraft-server:java21-alpine'

[env]
ALLOW_FLIGHT = 'TRUE'
AUTOSTOP_PERIOD = '10'
AUTOSTOP_TIMEOUT_EST = '3600'
AUTOSTOP_TIMEOUT_INIT = '1800'
DIFFICULTY = 'normal'
ENABLE_AUTOSTOP = 'TRUE'
ENABLE_ROLLING_LOGS = 'true'
ENABLE_WHITELIST = 'true'
ENFORCE_WHITELIST = 'true'
EULA = 'true'
LEVEL = 'world1'
MEMORY = '1G'
MODE = 'survival'
MOTD = 'lets go spelunking'
OPS_FILE = 'https://github.com/jfreedman0212/mc-vanilla-server/releases/latest/download/ops.json'
OVERRIDE_OPS = 'true'
OVERRIDE_WHITELIST = 'true'
RCON_CMDS_STARTUP = "    /gamerule keepInventory true\n    /gamerule playersSleepingPercentage 1\n  "
SEED = 'ingodwethrust'
SERVER_NAME = 'in-god-we-thrust'
SPAWN_PROTECTION = '0'
TYPE = 'VANILLA'
VERSION = '1.21.3'

[[mounts]]
source = 'mc_data'
destination = '/data'


[[services]]
internal_port = 25565
protocol = "tcp"
ports = { port = 25565 }
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 0
concurrency = { type = "connections", hard_limit = 25, soft_limit = 20 }

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
